openapi: "3.1.0"
info:
  title: "  Lagersystem API"
  description: "API to the Lagersystem Backend"
  version: "1.0.0"
paths:
  /:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Hello World!"